Mlh0079 5284 add edl authentication
ghrcdaac/cumulus-api pull request #21
Opened 2023-08-23 17:59 UTC by Michaellh0079

2023-08-28 15:28 UTC, camposeddie commented on cumulus_api/main.py
> +    def __init__(self, token=None, config_file=None):
`config_file` should remain `config_path` 
Updating will require py-cumulus-api users to update this variable name if already set within class instantiation and the update doesn't provide any additional context/functionality beyond a name change

2023-08-28 16:47 UTC, camposeddie commented
This PR needs accompanying updates to `env.sh.example` and `config_sample.cfg`

2023-08-28 16:47 UTC, camposeddie requested changes
Missing env file updates

2023-08-29 16:11 UTC, camposeddie commented on README.md
> +BASE_URL=************              // URS URL (https://uat.urs.earthdata.nasa.gov/)
defined here but not in env.sh.example

2023-08-29 16:11 UTC, camposeddie commented on README.md
> +USER_NAME=************             // URS username
wrong variable name

2023-08-29 16:11 UTC, camposeddie commented on README.md
> +USER_PASSWORD=************         // URS password
wrong variable name

2023-08-29 16:12 UTC, camposeddie commented on README.md
> +LAUNCHPAD_URL=*****                // most likely https://api.launchpad.nasa.gov/icam/api/sm/v1/gettoken
missing local certificate/passphrase variables

2023-08-29 16:12 UTC, camposeddie commented on README.md
> +BASE_URL=************              // URS URL (https://uat.urs.earthdata.nasa.gov/)
included here but not in actual env.sh.example file

2023-08-29 16:12 UTC, camposeddie commented on README.md
> +USER_NAME=************             // URS username
see above comments for wrong variable names

2023-08-29 16:13 UTC, camposeddie commented on README.md
> +If you are running this tool locally then you need to add your AWS_PROFILE name to the config.
not necessary for anything other than launchpad hosted credentials

2023-08-29 16:13 UTC, camposeddie commented on config_sample.cfg
>  LAUNCHPAD_PASSPHRASE=*****         // LAUNCHPAD Passphrase
wrong variable name and no inclusion of cloud hosted launchpad credentials

2023-08-29 16:14 UTC, camposeddie commented on config_sample.cfg
>  USER_NAME=************             // URS username
see above wrong variable name issue

2023-08-29 16:15 UTC, camposeddie commented on env.sh.example
> +# Launchpad
missing local launchpad variables

2023-08-29 16:15 UTC, camposeddie commented on env.sh.example
> +export USER_NAME=[REDACTED]
wrong variable names

2023-08-30 13:29 UTC, camposeddie commented on README.md
> +If you are running this tool locally then you need to add your AWS_PROFILE name to the config.
Is `AWS_PROFILE` needed locally if you are using EDL credentials or locally hosted launchpad credentials?

2023-08-31 12:43 UTC, Michaellh0079 commented on README.md
> +If you are running this tool locally then you need to add your AWS_PROFILE name to the config.
I don't believe so. I did not add this statement but only corrected the grammar. If you could capture any other additional requests you have into a single list and post them I will address them.

2023-08-31 13:57 UTC, camposeddie commented on README.md
> +If you are running this tool locally then you need to add your AWS_PROFILE name to the config.
Everything else looks good 👍

2023-08-31 15:47 UTC, camposeddie approved these changes

2023-08-31 16:15 UTC, merged